### ISSUE TITLE
Im getting some error.

### ISSUE THREAD

**Issue by khoroshyy** [Phyks/BMC#30]
I have installed BMC but cannot get it working.
This is the usual error:
________________________________
bmc.py import vlada.pdf 
DOI for vlada.pdf is 10.1002/wrna.1254.
Traceback (most recent call last):
  File "/usr/local/bin/bmc.py", line 584, in <module>
    args.tag, not args.inplace)
  File "/usr/local/bin/bmc.py", line 185, in addFile
    bibtex_string = tools.parsed2Bibtex(bibtex)
  File "/usr/local/lib/python2.7/dist-packages/libbmc/tools.py", line 49, in parsed2Bibtex
    bibtex = '@'+parsed['type']+'{'+parsed['id']+",\n"
KeyError: u'type'
___________________________________
I have bibtexparser 0.6.1 installed. Can it be the problem?
Thanks.
Petro

**Comment by khoroshyy** [comment]
It looks like there is a change between bibtexparser 0.6.0 and 0.6.1
-------------------------------------
* API: Previous type and id keywords which are automatically added to
the dictionnary are now ENTRYTYPE and ID, respectively (#42).
* ENH: comma first syntax support (#49) by Michal Grochmal.
------------------------------------

**Comment by Phyks** [comment]
Yes that could be it. I'm abroad and cannot fix it right now, will fix asap. If you can fix and make a PR, I will happily review and merge :)

**Comment by khoroshyy** [comment]
I may try but I am git illiterate so far :)

**Comment by Phyks** [comment]
@khoroshyy I pushed some changes in the issue30 branch. If you cloned the repo with git, you can `git fetch; git checkout issue30` to switch to this branch. Else, you can download it directly from Github I think.

I do not have any possibility to test the modifications at the moment. If you can, please let me know if it fixes everything so that I could push it to master branch. Else, I will test it next week.

Thanks

**Comment by khoroshyy** [comment]
Hi, I have tried the new branch.
It still does not work.
---------------------------------------

Traceback (most recent call last):
  File "/usr/local/bin/bmc.py", line 584, in <module>
    args.tag, not args.inplace)
  File "/usr/local/bin/bmc.py", line 185, in addFile
    bibtex_string = tools.parsed2Bibtex(bibtex)
  File "/usr/local/lib/python2.7/dist-packages/libbmc/tools.py", line
49, in parsed2Bibtex
    bibtex = '@'+parsed['entrytype']+'{'+parsed['id']+",\n"
KeyError: u'entrytype'
------------------------------------------------------------
I did some editing on my local version
entrytype and id
actually have to be capitalized: ENTRYTYPE and ID


On 8/21/15, Lucas Verney <notifications@github.com> wrote:
> @khoroshyy I pushed some changes in the issue30 branch. If you cloned the
> repo with git, you can `git fetch; git checkout issue30` to switch to this
> branch. Else, you can download it directly from Github I think.
>
> I do not have any possibility to test the modifications at the moment. If
> you can, please let me know if it fixes everything so that I could push it
> to master branch. Else, I will test it next week.
>
> Thanks
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Phyks/BMC/issues/30#issuecomment-133572582


-- 
______________________________
Petro Khoroshyy
Department of Chemical Physics and Optics,
Faculty of Mathematics and Physics,
Charles University in Prague

**Comment by Phyks** [comment]
Should be fixed in issue30.

**Comment by khoroshyy** [comment]
Thanks, I will try it out.
I also wanted to point out a bibsearch script implemented here:
https://github.com/dschwilk/bibstuff


______________________________
Petro Khoroshyy
Department of Chemical Physics and Optics,
Faculty of Mathematics and Physics,
Charles University in Prague

**Comment by Phyks** [comment]
Sorry for the delay, should be ok by now. At least, it is working for me.
